# Generated by Django 6.1.1 (NetBox 4.7.2), then edited by hand.
#
# Manual addition: InstallLtreeTriggers installs the PostgreSQL triggers that
# maintain AssetRole.path and AssetRole.sort_path (the ltree tree).
# makemigrations does not create them. The operation and its SQL come from
# NetBox (utilities.ltree), the same as for DeviceRole in NetBox core.
#
# The ltree extension itself is installed by NetBox core migrations (dcim), so
# it is not created here. This also keeps "migrate netbox_assets zero" from
# trying to drop an extension that NetBox core depends on.

import django.contrib.postgres.indexes
import django.db.models.deletion
import netbox.models.deletion
import netbox.models.ltree
import taggit.managers
import utilities.fields
import utilities.json
from django.db import migrations, models

from utilities.ltree import InstallLtreeTriggers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dcim", "0251_fix_ltree_cascade_triggers"),
        ("extras", "0144_customfield_status"),
        ("tenancy", "0027_fix_ltree_cascade_triggers"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "path",
                    netbox.models.ltree.LtreeField(
                        blank=True, default="", editable=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("sort_path", models.TextField(blank=True, default="", editable=False)),
                (
                    "color",
                    utilities.fields.ColorField(blank=True, default="", max_length=6),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="netbox_assets.assetrole",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "asset role",
                "verbose_name_plural": "asset roles",
                "ordering": ("sort_path",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        InstallLtreeTriggers("netbox_assets_assetrole", name_column="name"),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.contact",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_asset",
                        to="dcim.device",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="dcim.devicetype",
                    ),
                ),
                (
                    "module",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_asset",
                        to="dcim.module",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="dcim.moduletype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "owning_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "rack",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_asset",
                        to="dcim.rack",
                    ),
                ),
                (
                    "rack_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="dcim.racktype",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="dcim.location",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="netbox_assets.assetrole",
                    ),
                ),
            ],
            options={
                "ordering": ("device_type", "module_type", "rack_type", "serial"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="assetrole",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="netbox_assets_role_path_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="assetrole",
            index=models.Index(
                fields=["sort_path"], name="netbox_assets_role_sort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetrole",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"),
                name="netbox_assets_assetrole_parent_name",
                nulls_distinct=False,
                violation_error_message="An asset role with this name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetrole",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"),
                name="netbox_assets_assetrole_parent_slug",
                nulls_distinct=False,
                violation_error_message="An asset role with this slug already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("device_type", "serial"),
                name="netbox_assets_asset_device_type_serial",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("module_type", "serial"),
                name="netbox_assets_asset_module_type_serial",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("rack_type", "serial"),
                name="netbox_assets_asset_rack_type_serial",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("owning_tenant", "asset_tag"),
                name="netbox_assets_asset_owning_tenant_asset_tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                models.F("asset_tag"),
                condition=models.Q(("owning_tenant__isnull", True)),
                name="netbox_assets_asset_asset_tag",
                violation_error_message="Asset with this Asset Tag and no Owning Tenant already exists.",
            ),
        ),
    ]
